import type { CardName, Faction } from "../../game/model";

export const CARD_ART_ALIAS: Partial<Record<CardName, string>> = {
  slash: "main/cards/card/slash.jpg",
  dodge: "main/cards/card/jink.jpg",
  peach: "main/cards/card/peach.jpg",
  duel: "main/cards/card/duel.jpg",
  dismantle: "main/cards/card/dismantlement.jpg",
  snatch: "main/cards/card/snatch.jpg",
  "borrowed-sword": "main/cards/card/collateral.jpg",
  "ex-nihilo": "main/cards/card/ex_nihilo.jpg",
  nullification: "main/cards/card/nullification.jpg",
  "arrow-barrage": "main/cards/card/archery_attack.jpg",
  "barbarian-invasion": "main/cards/card/savage_assault.jpg",
  "peach-garden": "main/cards/card/god_salvation.jpg",
  harvest: "main/cards/card/amazing_grace.jpg",
  indulgence: "main/cards/card/indulgence.jpg",
  lightning: "main/cards/card/lightning.jpg",
};

export const EQUIP_ART_ALIAS: Partial<Record<CardName, string>> = {
  crossbow: "main/cards/card/Crossbow.jpg",
  "qinggang-sword": "main/cards/card/QinggangSword.jpg",
  "gender-swords": "main/cards/card/DoubleSword.jpg",
  "ice-sword": "main/cards/card/IceSword.jpg",
  "rock-cleaving-axe": "main/cards/card/Axe.jpg",
  "green-dragon-blade": "main/cards/card/Blade.jpg",
  "serpent-spear": "main/cards/card/Spear.jpg",
  halberd: "main/cards/card/Halberd.jpg",
  "qilin-bow": "main/cards/card/KylinBow.jpg",
  "bagua-formation": "main/cards/card/EightDiagram.jpg",
  "renwang-shield": "main/cards/card/RenwangShield.jpg",
  jueying: "main/cards/card/JueYing.jpg",
  "zhaohuang-feidian": "main/cards/card/ZhuaHuangFeiDian.jpg",
  dilu: "main/cards/card/DiLu.jpg",
  dayuan: "main/cards/card/DaYuan.jpg",
  "red-hare": "main/cards/card/ChiTu.jpg",
  zixing: "main/cards/card/ZiXing.jpg",
};

export const EQUIP_ICON_ALIAS: Partial<Record<CardName, string>> = {
  crossbow: "main/ui/equips/Crossbow.png",
  "qinggang-sword": "main/ui/equips/QinggangSword.png",
  "gender-swords": "main/ui/equips/DoubleSword.png",
  "ice-sword": "main/ui/equips/IceSword.png",
  "rock-cleaving-axe": "main/ui/equips/Axe.png",
  "green-dragon-blade": "main/ui/equips/Blade.png",
  "serpent-spear": "main/ui/equips/Spear.png",
  halberd: "main/ui/equips/Halberd.png",
  "qilin-bow": "main/ui/equips/KylinBow.png",
  "bagua-formation": "main/ui/equips/EightDiagram.png",
  "renwang-shield": "main/ui/equips/RenwangShield.png",
  jueying: "main/ui/equips/JueYing.png",
  "zhaohuang-feidian": "main/ui/equips/ZhuaHuangFeiDian.png",
  dilu: "main/ui/equips/DiLu.png",
  dayuan: "main/ui/equips/DaYuan.png",
  "red-hare": "main/ui/equips/ChiTu.png",
  zixing: "main/ui/equips/ZiXing.png",
};

export const GENERAL_PORTRAIT_ALIAS: Record<string, string> = {
  "cao-cao": "main/generals/avatar/caocao.png",
  "sima-yi": "main/generals/avatar/simayi.png",
  "xiahou-dun": "main/generals/avatar/xiahoudun.png",
  "zhang-liao": "main/generals/avatar/zhangliao.png",
  "xu-chu": "main/generals/avatar/xuchu.png",
  "guo-jia": "main/generals/avatar/guojia.png",
  "zhen-ji": "main/generals/avatar/zhenji.png",
  "liu-bei": "main/generals/avatar/liubei.png",
  "guan-yu": "main/generals/avatar/guanyu.png",
  "zhang-fei": "main/generals/avatar/zhangfei.png",
  "zhuge-liang": "main/generals/avatar/zhugeliang.png",
  "zhao-yun": "main/generals/avatar/zhaoyun.png",
  "ma-chao": "main/generals/avatar/machao.png",
  "huang-yueying": "main/generals/avatar/huangyueying.png",
  "sun-quan": "main/generals/avatar/sunquan.png",
  "gan-ning": "main/generals/avatar/ganning.png",
  "lu-meng": "main/generals/avatar/lvmeng.png",
  "huang-gai": "main/generals/avatar/huanggai.png",
  "zhou-yu": "main/generals/avatar/zhouyu.png",
  "da-qiao": "main/generals/avatar/daqiao.png",
  "lu-xun": "main/generals/avatar/luxun.png",
  "sun-shangxiang": "main/generals/avatar/sunshangxiang.png",
  "hua-tuo": "main/generals/avatar/huatuo.png",
  "lu-bu": "main/generals/avatar/lvbu.png",
  "diao-chan": "main/generals/avatar/diaochan.png",
  "hua-xiong": "main/generals/avatar/huaxiong.png",
  "yuan-shu": "main/generals/avatar/yuanshu.png",
};

export const GENERAL_CARD_ALIAS: Record<string, string> = {
  "cao-cao": "main/generals/card/caocao.jpg",
  "sima-yi": "main/generals/card/simayi.jpg",
  "xiahou-dun": "main/generals/card/xiahoudun.jpg",
  "zhang-liao": "main/generals/card/zhangliao.jpg",
  "xu-chu": "main/generals/card/xuchu.jpg",
  "guo-jia": "main/generals/card/guojia.jpg",
  "zhen-ji": "main/generals/card/zhenji.jpg",
  "liu-bei": "main/generals/card/liubei.jpg",
  "guan-yu": "main/generals/card/guanyu.jpg",
  "zhang-fei": "main/generals/card/zhangfei.jpg",
  "zhuge-liang": "main/generals/card/zhugeliang.jpg",
  "zhao-yun": "main/generals/card/zhaoyun.jpg",
  "ma-chao": "main/generals/card/machao.jpg",
  "huang-yueying": "main/generals/card/huangyueying.jpg",
  "sun-quan": "main/generals/card/sunquan.jpg",
  "gan-ning": "main/generals/card/ganning.jpg",
  "lu-meng": "main/generals/card/lvmeng.jpg",
  "huang-gai": "main/generals/card/huanggai.jpg",
  "zhou-yu": "main/generals/card/zhouyu.jpg",
  "da-qiao": "main/generals/card/daqiao.jpg",
  "lu-xun": "main/generals/card/luxun.jpg",
  "sun-shangxiang": "main/generals/card/sunshangxiang.jpg",
  "hua-tuo": "main/generals/card/huatuo.jpg",
  "lu-bu": "main/generals/card/lvbu.jpg",
  "diao-chan": "main/generals/card/diaochan.jpg",
  "hua-xiong": "main/generals/card/huaxiong.jpg",
  "yuan-shu": "main/generals/card/yuanshu.jpg",
};

export const GENERALS_WITHOUT_PORTRAIT = [] as const;

export const FACTION_ICON_ALIAS: Record<Faction, string> = {
  wei: "main/ui/kingdom/icon/wei.png",
  shu: "main/ui/kingdom/icon/shu.png",
  wu: "main/ui/kingdom/icon/wu.png",
  qun: "main/ui/kingdom/icon/qun.png",
};
