import type { CardName, Faction } from "../../game/model";

export const CARD_ART_ALIAS: Partial<Record<CardName, string>> = {
  slash: "cards/card/slash.jpg",
  dodge: "cards/card/jink.jpg",
  peach: "cards/card/peach.jpg",
  duel: "cards/card/duel.jpg",
  dismantle: "cards/card/dismantlement.jpg",
  snatch: "cards/card/snatch.jpg",
  "borrowed-sword": "cards/card/collateral.jpg",
  "ex-nihilo": "cards/card/ex_nihilo.jpg",
  nullification: "cards/card/nullification.jpg",
  "arrow-barrage": "cards/card/archery_attack.jpg",
  "barbarian-invasion": "cards/card/savage_assault.jpg",
  "peach-garden": "cards/card/god_salvation.jpg",
  harvest: "cards/card/amazing_grace.jpg",
  indulgence: "cards/card/indulgence.jpg",
  lightning: "cards/card/lightning.jpg",
};

export const EQUIP_ART_ALIAS: Partial<Record<CardName, string>> = {
  crossbow: "cards/card/Crossbow.jpg",
  "qinggang-sword": "cards/card/QinggangSword.jpg",
  "gender-swords": "cards/card/DoubleSword.jpg",
  "ice-sword": "cards/card/IceSword.jpg",
  "rock-cleaving-axe": "cards/card/Axe.jpg",
  "green-dragon-blade": "cards/card/Blade.jpg",
  "serpent-spear": "cards/card/Spear.jpg",
  halberd: "cards/card/Halberd.jpg",
  "qilin-bow": "cards/card/KylinBow.jpg",
  "bagua-formation": "cards/card/EightDiagram.jpg",
  "renwang-shield": "cards/card/RenwangShield.jpg",
  jueying: "cards/card/JueYing.jpg",
  "zhaohuang-feidian": "cards/card/ZhuaHuangFeiDian.jpg",
  dilu: "cards/card/DiLu.jpg",
  dayuan: "cards/card/DaYuan.jpg",
  "red-hare": "cards/card/ChiTu.jpg",
  zixing: "cards/card/ZiXing.jpg",
};

export const EQUIP_ICON_ALIAS: Partial<Record<CardName, string>> = {
  crossbow: "ui/equips/Crossbow.png",
  "qinggang-sword": "ui/equips/QinggangSword.png",
  "gender-swords": "ui/equips/DoubleSword.png",
  "ice-sword": "ui/equips/IceSword.png",
  "rock-cleaving-axe": "ui/equips/Axe.png",
  "green-dragon-blade": "ui/equips/Blade.png",
  "serpent-spear": "ui/equips/Spear.png",
  halberd: "ui/equips/Halberd.png",
  "qilin-bow": "ui/equips/KylinBow.png",
  "bagua-formation": "ui/equips/EightDiagram.png",
  "renwang-shield": "ui/equips/RenwangShield.png",
  jueying: "ui/equips/JueYing.png",
  "zhaohuang-feidian": "ui/equips/ZhuaHuangFeiDian.png",
  dilu: "ui/equips/DiLu.png",
  dayuan: "ui/equips/DaYuan.png",
  "red-hare": "ui/equips/ChiTu.png",
  zixing: "ui/equips/ZiXing.png",
};

export const GENERAL_PORTRAIT_ALIAS: Record<string, string> = {
  "cao-cao": "generals/avatar/caocao.png",
  "sima-yi": "generals/avatar/simayi.png",
  "xiahou-dun": "generals/avatar/xiahoudun.png",
  "zhang-liao": "generals/avatar/zhangliao.png",
  "xu-chu": "generals/avatar/xuchu.png",
  "guo-jia": "generals/avatar/guojia.png",
  "zhen-ji": "generals/avatar/zhenji.png",
  "liu-bei": "generals/avatar/liubei.png",
  "guan-yu": "generals/avatar/guanyu.png",
  "zhang-fei": "generals/avatar/zhangfei.png",
  "zhuge-liang": "generals/avatar/zhugeliang.png",
  "zhao-yun": "generals/avatar/zhaoyun.png",
  "ma-chao": "generals/avatar/machao.png",
  "huang-yueying": "generals/avatar/huangyueying.png",
  "sun-quan": "generals/avatar/sunquan.png",
  "gan-ning": "generals/avatar/ganning.png",
  "lu-meng": "generals/avatar/lvmeng.png",
  "huang-gai": "generals/avatar/huanggai.png",
  "zhou-yu": "generals/avatar/zhouyu.png",
  "da-qiao": "generals/avatar/daqiao.png",
  "lu-xun": "generals/avatar/luxun.png",
  "sun-shangxiang": "generals/avatar/sunshangxiang.png",
  "hua-tuo": "generals/avatar/huatuo.png",
  "lu-bu": "generals/avatar/lvbu.png",
  "diao-chan": "generals/avatar/diaochan.png",
  "hua-xiong": "generals/avatar/huaxiong.png",
  "yuan-shu": "generals/avatar/yuanshu.png",
};

export const GENERAL_CARD_ALIAS: Record<string, string> = {
  "cao-cao": "generals/card/caocao.jpg",
  "sima-yi": "generals/card/simayi.jpg",
  "xiahou-dun": "generals/card/xiahoudun.jpg",
  "zhang-liao": "generals/card/zhangliao.jpg",
  "xu-chu": "generals/card/xuchu.jpg",
  "guo-jia": "generals/card/guojia.jpg",
  "zhen-ji": "generals/card/zhenji.jpg",
  "liu-bei": "generals/card/liubei.jpg",
  "guan-yu": "generals/card/guanyu.jpg",
  "zhang-fei": "generals/card/zhangfei.jpg",
  "zhuge-liang": "generals/card/zhugeliang.jpg",
  "zhao-yun": "generals/card/zhaoyun.jpg",
  "ma-chao": "generals/card/machao.jpg",
  "huang-yueying": "generals/card/huangyueying.jpg",
  "sun-quan": "generals/card/sunquan.jpg",
  "gan-ning": "generals/card/ganning.jpg",
  "lu-meng": "generals/card/lvmeng.jpg",
  "huang-gai": "generals/card/huanggai.jpg",
  "zhou-yu": "generals/card/zhouyu.jpg",
  "da-qiao": "generals/card/daqiao.jpg",
  "lu-xun": "generals/card/luxun.jpg",
  "sun-shangxiang": "generals/card/sunshangxiang.jpg",
  "hua-tuo": "generals/card/huatuo.jpg",
  "lu-bu": "generals/card/lvbu.jpg",
  "diao-chan": "generals/card/diaochan.jpg",
  "hua-xiong": "generals/card/huaxiong.jpg",
  "yuan-shu": "generals/card/yuanshu.jpg",
};

export const GENERALS_WITHOUT_PORTRAIT = [] as const;

export const FACTION_ICON_ALIAS: Record<Faction, string> = {
  wei: "ui/kingdom/icon/wei.png",
  shu: "ui/kingdom/icon/shu.png",
  wu: "ui/kingdom/icon/wu.png",
  qun: "ui/kingdom/icon/qun.png",
};
