import type {
  CardDefinition,
  CardName,
  PhysicalCard,
  Rank,
  Suit,
} from "../model";

export const CARD_DEFINITIONS: Record<CardName, CardDefinition> = {
  slash: { id: "slash", name: "Sát", chineseName: "杀", kind: "basic" },
  dodge: { id: "dodge", name: "Thiểm", chineseName: "闪", kind: "basic" },
  peach: { id: "peach", name: "Đào", chineseName: "桃", kind: "basic" },
  duel: { id: "duel", name: "Quyết Đấu", chineseName: "决斗", kind: "trick" },
  dismantle: {
    id: "dismantle",
    name: "Quá Hà Sách Kiều",
    chineseName: "过河拆桥",
    kind: "trick",
  },
  snatch: {
    id: "snatch",
    name: "Thuận Thủ Khiên Dương",
    chineseName: "顺手牵羊",
    kind: "trick",
  },
  "borrowed-sword": {
    id: "borrowed-sword",
    name: "Tá Đao Sát Nhân",
    chineseName: "借刀杀人",
    kind: "trick",
  },
  "ex-nihilo": {
    id: "ex-nihilo",
    name: "Vô Trung Sinh Hữu",
    chineseName: "无中生有",
    kind: "trick",
  },
  nullification: {
    id: "nullification",
    name: "Vô Giải Khả Kích",
    chineseName: "无懈可击",
    kind: "trick",
  },
  "arrow-barrage": {
    id: "arrow-barrage",
    name: "Vạn Tiễn Tề Phát",
    chineseName: "万箭齐发",
    kind: "trick",
  },
  "barbarian-invasion": {
    id: "barbarian-invasion",
    name: "Nam Man Nhập Xâm",
    chineseName: "南蛮入侵",
    kind: "trick",
  },
  "peach-garden": {
    id: "peach-garden",
    name: "Đào Viên Kết Nghĩa",
    chineseName: "桃园结义",
    kind: "trick",
  },
  harvest: {
    id: "harvest",
    name: "Ngũ Cốc Phong Đăng",
    chineseName: "五谷丰登",
    kind: "trick",
  },
  indulgence: {
    id: "indulgence",
    name: "Lạc Bất Tư Thục",
    chineseName: "乐不思蜀",
    kind: "delayed-trick",
  },
  lightning: {
    id: "lightning",
    name: "Thiểm Điện",
    chineseName: "闪电",
    kind: "delayed-trick",
  },
  crossbow: {
    id: "crossbow",
    name: "Gia Cát Liên Nỗ",
    chineseName: "诸葛连弩",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 1,
  },
  "qinggang-sword": {
    id: "qinggang-sword",
    name: "Thanh Công Kiếm",
    chineseName: "青釭剑",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 2,
  },
  "gender-swords": {
    id: "gender-swords",
    name: "Thư Hùng Song Cổ Kiếm",
    chineseName: "雌雄双股剑",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 2,
  },
  "ice-sword": {
    id: "ice-sword",
    name: "Hàn Băng Kiếm",
    chineseName: "寒冰剑",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 2,
  },
  "rock-cleaving-axe": {
    id: "rock-cleaving-axe",
    name: "Quán Thạch Phủ",
    chineseName: "贯石斧",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 3,
  },
  "green-dragon-blade": {
    id: "green-dragon-blade",
    name: "Thanh Long Yển Nguyệt Đao",
    chineseName: "青龙偃月刀",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 3,
  },
  "serpent-spear": {
    id: "serpent-spear",
    name: "Trượng Bát Xà Mâu",
    chineseName: "丈八蛇矛",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 3,
  },
  halberd: {
    id: "halberd",
    name: "Phương Thiên Họa Kích",
    chineseName: "方天画戟",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 4,
  },
  "qilin-bow": {
    id: "qilin-bow",
    name: "Kỳ Lân Cung",
    chineseName: "麒麟弓",
    kind: "equipment",
    equipmentSlot: "weapon",
    attackRange: 5,
  },
  "bagua-formation": {
    id: "bagua-formation",
    name: "Bát Quái Trận",
    chineseName: "八卦阵",
    kind: "equipment",
    equipmentSlot: "armor",
  },
  "renwang-shield": {
    id: "renwang-shield",
    name: "Nhân Vương Thuẫn",
    chineseName: "仁王盾",
    kind: "equipment",
    equipmentSlot: "armor",
  },
  jueying: {
    id: "jueying",
    name: "Tuyệt Ảnh",
    chineseName: "绝影",
    kind: "equipment",
    equipmentSlot: "defensive-mount",
  },
  "zhaohuang-feidian": {
    id: "zhaohuang-feidian",
    name: "Trảo Hoàng Phi Điện",
    chineseName: "爪黄飞电",
    kind: "equipment",
    equipmentSlot: "defensive-mount",
  },
  dilu: {
    id: "dilu",
    name: "Đích Lô",
    chineseName: "的卢",
    kind: "equipment",
    equipmentSlot: "defensive-mount",
  },
  dayuan: {
    id: "dayuan",
    name: "Đại Uyển",
    chineseName: "大宛",
    kind: "equipment",
    equipmentSlot: "offensive-mount",
  },
  "red-hare": {
    id: "red-hare",
    name: "Xích Thố",
    chineseName: "赤兔",
    kind: "equipment",
    equipmentSlot: "offensive-mount",
  },
  zixing: {
    id: "zixing",
    name: "Tử Tinh",
    chineseName: "紫骍",
    kind: "equipment",
    equipmentSlot: "offensive-mount",
  },
};

type CardSpec = readonly [Suit, Rank, CardName, edition?: "ex"];

const CARD_SPECS: CardSpec[] = [
  ["heart", "A", "peach-garden"],
  ["heart", "A", "arrow-barrage"],
  ["heart", "2", "dodge"],
  ["heart", "2", "dodge"],
  ["heart", "3", "peach"],
  ["heart", "3", "harvest"],
  ["heart", "4", "peach"],
  ["heart", "4", "harvest"],
  ["heart", "5", "qilin-bow"],
  ["heart", "5", "red-hare"],
  ["heart", "6", "peach"],
  ["heart", "6", "indulgence"],
  ["heart", "7", "peach"],
  ["heart", "7", "ex-nihilo"],
  ["heart", "8", "peach"],
  ["heart", "8", "ex-nihilo"],
  ["heart", "9", "peach"],
  ["heart", "9", "ex-nihilo"],
  ["heart", "10", "slash"],
  ["heart", "10", "slash"],
  ["heart", "J", "slash"],
  ["heart", "J", "ex-nihilo"],
  ["heart", "Q", "peach"],
  ["heart", "Q", "dismantle"],
  ["heart", "Q", "lightning", "ex"],
  ["heart", "K", "dodge"],
  ["heart", "K", "zhaohuang-feidian"],

  ["spade", "A", "duel"],
  ["spade", "A", "lightning"],
  ["spade", "2", "gender-swords"],
  ["spade", "2", "bagua-formation"],
  ["spade", "2", "ice-sword", "ex"],
  ["spade", "3", "dismantle"],
  ["spade", "3", "snatch"],
  ["spade", "4", "dismantle"],
  ["spade", "4", "snatch"],
  ["spade", "5", "green-dragon-blade"],
  ["spade", "5", "jueying"],
  ["spade", "6", "indulgence"],
  ["spade", "6", "qinggang-sword"],
  ["spade", "7", "slash"],
  ["spade", "7", "barbarian-invasion"],
  ["spade", "8", "slash"],
  ["spade", "8", "slash"],
  ["spade", "9", "slash"],
  ["spade", "9", "slash"],
  ["spade", "10", "slash"],
  ["spade", "10", "slash"],
  ["spade", "J", "snatch"],
  ["spade", "J", "nullification"],
  ["spade", "Q", "dismantle"],
  ["spade", "Q", "serpent-spear"],
  ["spade", "K", "barbarian-invasion"],
  ["spade", "K", "dayuan"],

  ["diamond", "A", "crossbow"],
  ["diamond", "A", "duel"],
  ["diamond", "2", "dodge"],
  ["diamond", "2", "dodge"],
  ["diamond", "3", "dodge"],
  ["diamond", "3", "snatch"],
  ["diamond", "4", "dodge"],
  ["diamond", "4", "snatch"],
  ["diamond", "5", "dodge"],
  ["diamond", "5", "rock-cleaving-axe"],
  ["diamond", "6", "slash"],
  ["diamond", "6", "dodge"],
  ["diamond", "7", "slash"],
  ["diamond", "7", "dodge"],
  ["diamond", "8", "slash"],
  ["diamond", "8", "dodge"],
  ["diamond", "9", "slash"],
  ["diamond", "9", "dodge"],
  ["diamond", "10", "slash"],
  ["diamond", "10", "dodge"],
  ["diamond", "J", "dodge"],
  ["diamond", "J", "dodge"],
  ["diamond", "Q", "peach"],
  ["diamond", "Q", "halberd"],
  ["diamond", "Q", "nullification", "ex"],
  ["diamond", "K", "slash"],
  ["diamond", "K", "zixing"],

  ["club", "A", "duel"],
  ["club", "A", "crossbow"],
  ["club", "2", "slash"],
  ["club", "2", "bagua-formation"],
  ["club", "2", "renwang-shield", "ex"],
  ["club", "3", "slash"],
  ["club", "3", "dismantle"],
  ["club", "4", "slash"],
  ["club", "4", "dismantle"],
  ["club", "5", "slash"],
  ["club", "5", "dilu"],
  ["club", "6", "slash"],
  ["club", "6", "indulgence"],
  ["club", "7", "slash"],
  ["club", "7", "barbarian-invasion"],
  ["club", "8", "slash"],
  ["club", "8", "slash"],
  ["club", "9", "slash"],
  ["club", "9", "slash"],
  ["club", "10", "slash"],
  ["club", "10", "slash"],
  ["club", "J", "slash"],
  ["club", "J", "slash"],
  ["club", "Q", "borrowed-sword"],
  ["club", "Q", "nullification"],
  ["club", "K", "borrowed-sword"],
  ["club", "K", "nullification"],
];

export const STANDARD_2013_DECK: PhysicalCard[] = CARD_SPECS.map(
  ([suit, rank, definitionID, edition], index) => ({
    id: `card-${String(index + 1).padStart(3, "0")}`,
    definitionID,
    suit,
    rank,
    edition: edition ?? "standard",
  }),
);

export function getCardDefinition(card: PhysicalCard): CardDefinition {
  return CARD_DEFINITIONS[card.definitionID];
}
