import type { GeneralDefinition, Role, SkillDefinition } from "../model";

export const SKILLS: Record<string, SkillDefinition> = {
  "jian-xiong": { id: "jian-xiong", name: "Gian Hùng", chineseName: "奸雄" },
  "hu-jia": {
    id: "hu-jia",
    name: "Hộ Giá",
    chineseName: "护驾",
    lordSkill: true,
  },
  "fan-kui": { id: "fan-kui", name: "Phản Quỹ", chineseName: "反馈" },
  "gui-cai": { id: "gui-cai", name: "Quỷ Tài", chineseName: "鬼才" },
  "gang-lie": { id: "gang-lie", name: "Cương Liệt", chineseName: "刚烈" },
  "tu-xi": { id: "tu-xi", name: "Đột Tập", chineseName: "突袭" },
  "luo-yi": { id: "luo-yi", name: "Lõa Y", chineseName: "裸衣" },
  "tian-du": { id: "tian-du", name: "Thiên Đố", chineseName: "天妒" },
  "yi-ji": { id: "yi-ji", name: "Di Kế", chineseName: "遗计" },
  "luo-shen": { id: "luo-shen", name: "Lạc Thần", chineseName: "洛神" },
  "qing-guo": { id: "qing-guo", name: "Khuynh Quốc", chineseName: "倾国" },
  "ren-de": { id: "ren-de", name: "Nhân Đức", chineseName: "仁德" },
  "ji-jiang": {
    id: "ji-jiang",
    name: "Kích Tướng",
    chineseName: "激将",
    lordSkill: true,
  },
  "wu-sheng": { id: "wu-sheng", name: "Võ Thánh", chineseName: "武圣" },
  "pao-xiao": { id: "pao-xiao", name: "Bào Hao", chineseName: "咆哮" },
  "guan-xing": { id: "guan-xing", name: "Quan Tinh", chineseName: "观星" },
  "kong-cheng": {
    id: "kong-cheng",
    name: "Không Thành",
    chineseName: "空城",
    lockedSkill: true,
  },
  "long-dan": { id: "long-dan", name: "Long Đảm", chineseName: "龙胆" },
  "ma-shu": {
    id: "ma-shu",
    name: "Mã Thuật",
    chineseName: "马术",
    lockedSkill: true,
  },
  "tie-ji": { id: "tie-ji", name: "Thiết Kỵ", chineseName: "铁骑" },
  "ji-zhi": { id: "ji-zhi", name: "Tập Trí", chineseName: "集智" },
  "qi-cai": {
    id: "qi-cai",
    name: "Kỳ Tài",
    chineseName: "奇才",
    lockedSkill: true,
  },
  "zhi-heng": { id: "zhi-heng", name: "Chế Hành", chineseName: "制衡" },
  "jiu-yuan": {
    id: "jiu-yuan",
    name: "Cứu Viện",
    chineseName: "救援",
    lordSkill: true,
    lockedSkill: true,
  },
  "qi-xi": { id: "qi-xi", name: "Kỳ Tập", chineseName: "奇袭" },
  "ke-ji": { id: "ke-ji", name: "Khắc Kỷ", chineseName: "克己" },
  "ku-rou": { id: "ku-rou", name: "Khổ Nhục", chineseName: "苦肉" },
  "ying-zi": { id: "ying-zi", name: "Anh Tư", chineseName: "英姿" },
  "fan-jian": { id: "fan-jian", name: "Phản Gián", chineseName: "反间" },
  "guo-se": { id: "guo-se", name: "Quốc Sắc", chineseName: "国色" },
  "liu-li": { id: "liu-li", name: "Lưu Ly", chineseName: "流离" },
  "qian-xun": {
    id: "qian-xun",
    name: "Khiêm Tốn",
    chineseName: "谦逊",
    lockedSkill: true,
  },
  "lian-ying": { id: "lian-ying", name: "Liên Doanh", chineseName: "连营" },
  "jie-yin": { id: "jie-yin", name: "Kết Nhân", chineseName: "结姻" },
  "xiao-ji": { id: "xiao-ji", name: "Kiêu Cơ", chineseName: "枭姬" },
  "ji-jiu": { id: "ji-jiu", name: "Cấp Cứu", chineseName: "急救" },
  "qing-nang": { id: "qing-nang", name: "Thanh Nang", chineseName: "青囊" },
  "wu-shuang": {
    id: "wu-shuang",
    name: "Vô Song",
    chineseName: "无双",
    lockedSkill: true,
  },
  "li-jian": { id: "li-jian", name: "Ly Gián", chineseName: "离间" },
  "bi-yue": { id: "bi-yue", name: "Bế Nguyệt", chineseName: "闭月" },
  "yao-wu": {
    id: "yao-wu",
    name: "Diệu Võ",
    chineseName: "耀武",
    lockedSkill: true,
  },
  "wang-zun": { id: "wang-zun", name: "Vọng Tôn", chineseName: "妄尊" },
  "tong-ji": {
    id: "tong-ji",
    name: "Đồng Tật",
    chineseName: "同疾",
    lockedSkill: true,
  },
};

export const GENERALS: GeneralDefinition[] = [
  {
    id: "cao-cao",
    name: "Tào Tháo",
    chineseName: "曹操",
    faction: "wei",
    gender: "male",
    maxHP: 4,
    skillIDs: ["jian-xiong", "hu-jia"],
  },
  {
    id: "sima-yi",
    name: "Tư Mã Ý",
    chineseName: "司马懿",
    faction: "wei",
    gender: "male",
    maxHP: 3,
    skillIDs: ["fan-kui", "gui-cai"],
  },
  {
    id: "xiahou-dun",
    name: "Hạ Hầu Đôn",
    chineseName: "夏侯惇",
    faction: "wei",
    gender: "male",
    maxHP: 4,
    skillIDs: ["gang-lie"],
  },
  {
    id: "zhang-liao",
    name: "Trương Liêu",
    chineseName: "张辽",
    faction: "wei",
    gender: "male",
    maxHP: 4,
    skillIDs: ["tu-xi"],
  },
  {
    id: "xu-chu",
    name: "Hứa Chử",
    chineseName: "许褚",
    faction: "wei",
    gender: "male",
    maxHP: 4,
    skillIDs: ["luo-yi"],
  },
  {
    id: "guo-jia",
    name: "Quách Gia",
    chineseName: "郭嘉",
    faction: "wei",
    gender: "male",
    maxHP: 3,
    skillIDs: ["tian-du", "yi-ji"],
  },
  {
    id: "zhen-ji",
    name: "Chân Cơ",
    chineseName: "甄姬",
    faction: "wei",
    gender: "female",
    maxHP: 3,
    skillIDs: ["luo-shen", "qing-guo"],
  },
  {
    id: "liu-bei",
    name: "Lưu Bị",
    chineseName: "刘备",
    faction: "shu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["ren-de", "ji-jiang"],
  },
  {
    id: "guan-yu",
    name: "Quan Vũ",
    chineseName: "关羽",
    faction: "shu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["wu-sheng"],
  },
  {
    id: "zhang-fei",
    name: "Trương Phi",
    chineseName: "张飞",
    faction: "shu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["pao-xiao"],
  },
  {
    id: "zhuge-liang",
    name: "Gia Cát Lượng",
    chineseName: "诸葛亮",
    faction: "shu",
    gender: "male",
    maxHP: 3,
    skillIDs: ["guan-xing", "kong-cheng"],
  },
  {
    id: "zhao-yun",
    name: "Triệu Vân",
    chineseName: "赵云",
    faction: "shu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["long-dan"],
  },
  {
    id: "ma-chao",
    name: "Mã Siêu",
    chineseName: "马超",
    faction: "shu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["ma-shu", "tie-ji"],
  },
  {
    id: "huang-yueying",
    name: "Hoàng Nguyệt Anh",
    chineseName: "黄月英",
    faction: "shu",
    gender: "female",
    maxHP: 3,
    skillIDs: ["ji-zhi", "qi-cai"],
  },
  {
    id: "sun-quan",
    name: "Tôn Quyền",
    chineseName: "孙权",
    faction: "wu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["zhi-heng", "jiu-yuan"],
  },
  {
    id: "gan-ning",
    name: "Cam Ninh",
    chineseName: "甘宁",
    faction: "wu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["qi-xi"],
  },
  {
    id: "lu-meng",
    name: "Lữ Mông",
    chineseName: "吕蒙",
    faction: "wu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["ke-ji"],
  },
  {
    id: "huang-gai",
    name: "Hoàng Cái",
    chineseName: "黄盖",
    faction: "wu",
    gender: "male",
    maxHP: 4,
    skillIDs: ["ku-rou"],
  },
  {
    id: "zhou-yu",
    name: "Chu Du",
    chineseName: "周瑜",
    faction: "wu",
    gender: "male",
    maxHP: 3,
    skillIDs: ["ying-zi", "fan-jian"],
  },
  {
    id: "da-qiao",
    name: "Đại Kiều",
    chineseName: "大乔",
    faction: "wu",
    gender: "female",
    maxHP: 3,
    skillIDs: ["guo-se", "liu-li"],
  },
  {
    id: "lu-xun",
    name: "Lục Tốn",
    chineseName: "陆逊",
    faction: "wu",
    gender: "male",
    maxHP: 3,
    skillIDs: ["qian-xun", "lian-ying"],
  },
  {
    id: "sun-shangxiang",
    name: "Tôn Thượng Hương",
    chineseName: "孙尚香",
    faction: "wu",
    gender: "female",
    maxHP: 3,
    skillIDs: ["jie-yin", "xiao-ji"],
  },
  {
    id: "hua-tuo",
    name: "Hoa Đà",
    chineseName: "华佗",
    faction: "qun",
    gender: "male",
    maxHP: 3,
    skillIDs: ["ji-jiu", "qing-nang"],
  },
  {
    id: "lu-bu",
    name: "Lữ Bố",
    chineseName: "吕布",
    faction: "qun",
    gender: "male",
    maxHP: 4,
    skillIDs: ["wu-shuang"],
  },
  {
    id: "diao-chan",
    name: "Điêu Thuyền",
    chineseName: "貂蝉",
    faction: "qun",
    gender: "female",
    maxHP: 3,
    skillIDs: ["li-jian", "bi-yue"],
  },
  {
    id: "hua-xiong",
    name: "Hoa Hùng",
    chineseName: "华雄",
    faction: "qun",
    gender: "male",
    maxHP: 6,
    skillIDs: ["yao-wu"],
  },
  {
    id: "yuan-shu",
    name: "Viên Thuật",
    chineseName: "袁术",
    faction: "qun",
    gender: "male",
    maxHP: 4,
    skillIDs: ["wang-zun", "tong-ji"],
  },
];

export const GENERALS_BY_ID = Object.fromEntries(
  GENERALS.map((general) => [general.id, general]),
);
export const LORD_GENERAL_IDS = ["cao-cao", "liu-bei", "sun-quan"] as const;

export function getActiveSkillIDs(generalID: string, role: Role): string[] {
  const general = GENERALS_BY_ID[generalID];
  if (!general) return [];
  return general.skillIDs.filter(
    (skillID) => role === "lord" || !SKILLS[skillID].lordSkill,
  );
}

export function hasLordSkill(generalID: string): boolean {
  return GENERALS_BY_ID[generalID]?.skillIDs.some(
    (skillID) => SKILLS[skillID].lordSkill,
  );
}
